region: ENC[AES256_GCM,data:iZjSmEiFA9ehAwIqHo0=,iv:lSMXD61BfIJO1W8xjreHppm0KRj1bBi/RJYiSy7RxMk=,tag:uKAucFXw58cCjuSES7nZ0w==,type:str]
compartment_id: ENC[AES256_GCM,data:jtANsS8nZRacR/aiY1UlrlLWkBKdS/elNdZafuUOiFvhwmOaDh70qVcXC4xFuZVml8ysY5xoR5+ugHiaunMO94//hVMJSTeKMyo+4XfzmZ4czuE=,iv:Ea3x1XkHxzZmEaNKvDstonXHzCcU6v9Bnwd7EmlL49s=,tag:fO+vWrcrLG+ytsC6wcclqg==,type:str]
github_user: ENC[AES256_GCM,data:5uJVcX1kj9c=,iv:m9uaetjA1vur0etrfW5P3SIUbCAJ4X5vCqXcgwP4RGE=,tag:gLHbZRaDHfUfV8Oz4tpRUg==,type:str]
github_repo: ENC[AES256_GCM,data:3jx+4Xwu6WllXhNHJq2c/U0=,iv:blpm/XGgLZADwGKR+Uz+ja7P503OAwX/Yd3a9kFlIQU=,tag:8dxv+4EOZFklaEmiTngdLg==,type:str]
github_path: ENC[AES256_GCM,data:7PX54Q+8x8Tv/R0QpKFI,iv:n12WYJQw/ItZ8U1b/8N5O+qJ4Y+ZGFytpdd4oU01pJM=,tag:UzcMqnQCR8kWdD9FeA0v/w==,type:str]
github_pat: ENC[AES256_GCM,data:apbwix2BL4dCbjx4JYO8SqYITAYiXHMtsRmTR+4u11nczZRUkfNmjw026QtfFP91bxREvz4AYCjHN4X3qdPKsOMEWt/Fow0tW9XJ2Jfs9Wm+0qxFe75gQPT17GYf,iv:nyXLaBS5HDMBX0B21mPr5tSBs+UhuOdglRKIHQFDUa8=,tag:gI+Uo3Yv1P5pTniehyGAVw==,type:str]
domain_name: ENC[AES256_GCM,data:tI+D9o9gMBjjSQ==,iv:RIDFUJmP23mK0q6UAu8teht554J4lTnO9f5vVUBmn7A=,tag:c8Gj41qGlzf0qLZP2Aj+ng==,type:str]
acme_email: ENC[AES256_GCM,data:6RkRufsLYQqlhnmBrVBj5gBVqHBtzGUX6j9dXy0FDAAzprUQ8hS/VLRROQ==,iv:xCK6+jr3itkum5C4DsuTeqkcdtQmhA0AnxPPbqWrfc8=,tag:UkCmHfx7TqhrnvLrjlrhEA==,type:str]
cloudflare_token: ENC[AES256_GCM,data:Th3aJ89y4DGHv3AJ9VX/SLOFq/szdVLdDadY+quqKiXK/60xXFixCyP3sOpfHktnj6QbBjU=,iv:kAgdqPBY24u8jsvLp/JP1l4B4P8fk85Gs1X/jzn8WqY=,tag:omQ+WqmJA29m4eHIkFTHZg==,type:str]
sops:
    age:
        - recipient: age1nu7vf3mgwds705rpfnvzlr20zkphh0tga4hc06xs7nmrxwmnsyvsp8sxzc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLamJha2I4aEVubDZSaEx1
            NVlaeEJhVXlqQmlHSWgwZkJFdmxQcFFEeFQ0Ck1ROEhjZW10MWxFU0hYTmNheWpv
            SkRTc3Rtb08wdG9oTENRZWJYL0JnOHMKLS0tIHNSbnNmdmd6TFNRQnhFM21oV2tS
            ZUdJTWd0d08rYzFCbTVJRUpHZlZETVkK8lkvuaUvkqw+oiBDvPS3SDpV1G5/G+gy
            +laBSJdVHOO59esiZtEHLxg9Zu7zLgfIJsnOgTvvyprhFYgyPPVl3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T11:11:12Z"
    mac: ENC[AES256_GCM,data:szsSzyabWGfsj7+PPFPWmY1fHgtGDyyKrNiWCW0khvhdoQZdEtbtSXIjl2Fxx2ztvQdy+JxY6aC7jjsW8lkWc4DpaYdDwehh5q/NMQb+jDEmuPz14slZGo2a8BTFoihF0rzdwA5MY+YgkNxTvrvB5r3b6cXnLr6O9VI0ksRwObQ=,iv:e1PbpfXUXIjZquUfMNi50/2y0efY9rtO5/OMY0ioJZ8=,tag:xZMOinX6BhllrX9aKicAMQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
